### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tylik1** [yanirclsr/MarTech#2]
The code doesn't work.
function topDomain() doesn't work in chrome, at least when running with local server.

Then on each request, even on first you get __ft + __lt cookies populated, while i believe that on first you only need __ft, while on others __lt

Also on local storage you get extra data set which doesn't contain any prefix

**Comment by dexm-pro** [comment]
@tylik1 the problem was specifically with running the script on localhost.
We fixed it now - can you please try again?
Regarding the ft and lt - if a visitor visits only once and fills out the form both first touch and last touch would be similar. Only if he has more visits (and comes from different sources) then the LT will be updated with the new data.

**Comment by dexm-pro** [comment]
@tylik1 the problem was specifically with running the script on localhost.
We fixed it now - can you please try again?
Regarding the ft and lt - if a visitor visits only once and fills out the form both first touch and last touch would be similar. Only if he has more visits (and comes from different sources) then the LT will be updated with the new data.

**Comment by tylik1** [comment]
( still no luck. my url looks like this: localhost:3000 
Maybe the port is the issue.
